### ISSUE TITLE
Home page layout 

### ISSUE THREAD

**Issue by VuongVu2103** [VuongVu2103/Laravel-Reactjs-Web-App#1]
The content of home page still basic . 
We need to make it better @tuongvan120111 check issues and give me your opinions . 
And you take care the home page please . 
Thank you

**Comment by tuongvan120111** [comment]
- I think we must have a category (suggest that on the top or left), pagination, search tool on the top,
- Maybe a discount price or some thing be know which one can be buy with a lower price (some case like that) than other store.
- Can resize each product a little bit because that size still too big but be careful css (that can be broken when u resize but i think it can't be a smart choose a template which we don't know clearly)
